version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
      production-minor-patch:
        applies-to: version-updates
        dependency-type: "production"
        update-types: ["patch", "minor"]
      dev-minor-patch:
        applies-to: version-updates
        dependency-type: "development"
        update-types: ["patch", "minor"]
